---
extends: default

rules:
    line-length:
        max: 300 # Allow very long lines for GitHub Actions expressions
    truthy: disable  # Conflicts with yamlfmt formatting
    comments-indentation: disable # Allow flexible comment indentation
    indentation:
        spaces: 2
