name: 'Setup Build Environment'
description: 'Install build dependencies for OpenBLAS compilation'
inputs:
  is-manylinux:
    description: 'Whether this is a manylinux container build'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if [[ "${{ inputs.is-manylinux }}" == "true" ]]; then
          if command -v yum &> /dev/null; then
            yum update -y
            yum install -y git cmake3 make gcc-c++ gfortran
            ln -sf /usr/bin/cmake3 /usr/bin/cmake || true
          elif command -v apt-get &> /dev/null; then
            apt-get update
            apt-get install -y git cmake build-essential gfortran
          fi
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install cmake gfortran
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install msys2
          C:\\tools\\msys64\\usr\\bin\\bash.exe -lc "pacman -S --noconfirm mingw-w64-x86_64-gcc-fortran"
          echo "C:\\tools\\msys64\\mingw64\\bin" >> $GITHUB_PATH
        fi