---
name: Setup Build Environment
description: Install build dependencies for OpenBLAS compilation
inputs:
  is-manylinux:
    description: Whether this is a manylinux container build
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Setup Fortran on Windows
      if: runner.os == 'Windows'
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: intel
