---
name: Build OpenBLAS

# Build configuration - see individual steps for variable usage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Run weekly on Sundays at 02:00 UTC to check for new OpenBLAS releases
    - cron: 0 2 * * 0
  workflow_dispatch:
    inputs:
      openblas_version:
        description: OpenBLAS version to build (e.g., v0.3.30, or leave empty for latest)
        required: false
        default: ''
        type: string
      is_nightly:
        description: Create nightly release (overwrites previous nightly)
        required: false
        default: false
        type: boolean

env:
  # Use input version if provided, otherwise let build script fetch latest
  OPENBLAS_VERSION: ${{ inputs.openblas_version || '' }}
  IS_NIGHTLY: ${{ inputs.is_nightly || github.event_name == 'schedule' }}

jobs:
  check-version:
    uses: ./.github/workflows/check-openblas.yml
    with:
      version: ${{ inputs.openblas_version || '' }}
      is-nightly: ${{ inputs.is_nightly || github.event_name == 'schedule' }}
    secrets: inherit

  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    needs: check-version
    if: needs.check-version.outputs.should-build == 'true'

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux manylinux builds
          # - runner: ubuntu-latest
          #   toolset: devtoolset-10
          #   name: manylinux2014_x86_64
          # - runner: ubuntu-latest
          #   toolset: gcc-toolset-14
          #   name: manylinux_2_28_x86_64
          # - runner: ubuntu-latest
          #   toolset: gcc-toolset-14
          #   name: manylinux_2_34_x86_64
          # #  Neoverse not supported by GCC 10, so we skip manylinux2014_aarch64
          # - runner: ubuntu-24.04-arm
          #   toolset: gcc-toolset-14
          #   name: manylinux_2_28_aarch64
          # - runner: ubuntu-24.04-arm
          #   toolset: gcc-toolset-14
          #   name: manylinux_2_34_aarch64
          # Native OS builds
          # - runner: windows-latest
          #   name: windows-x64
          # macOS builds
          - runner: macos-13
            name: macos-13-x64
          - runner: macos-14
            name: macos-14-arm64
          - runner: macos-15
            name: macos-15-arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        uses: ./.github/actions/setup-build-env
        with:
          is-manylinux: ${{ contains(matrix.name, 'manylinux') }}

      - name: Build OpenBLAS (Windows)
        if: ${{ contains(matrix.runner, 'windows') }}
        shell: msys2 {0}
        env:
          OPENBLAS_VERSION: ${{ needs.check-version.outputs.openblas-version }}
        run: |
          chmod +x scripts/build-openblas.sh
          ./scripts/build-openblas.sh

      - name: Build OpenBLAS (macOS)
        if: ${{ contains(matrix.runner, 'macos') }}
        shell: bash
        env:
          OPENBLAS_VERSION: ${{ needs.check-version.outputs.openblas-version }}
        run: |
          chmod +x scripts/build-openblas.sh
          ./scripts/build-openblas.sh

      - name: Build OpenBLAS (manylinux)
        if: ${{ contains(matrix.name, 'manylinux') }}
        shell: bash
        env:
          OPENBLAS_VERSION: ${{ needs.check-version.outputs.openblas-version }}
        run: |
          docker run --rm -v "$PWD:/workspace" -w /workspace --env-file <(env) \
            quay.io/pypa/${{ matrix.name }} \
            bash -c "source /opt/rh/${{ matrix.toolset }}/enable && chmod +x scripts/build-openblas.sh && ./scripts/build-openblas.sh"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openblas-${{ needs.check-version.outputs.openblas-version }}-${{ matrix.name }}
          path: install/
          if-no-files-found: error
          compression-level: 9
          retention-days: 30

  release:
    name: Create Release
    needs: [check-version, build]
    runs-on: ubuntu-latest
    if: |
      needs.check-version.result == 'success' &&
      (needs.build.result == 'success' || (needs.build.result == 'skipped' && needs.check-version.outputs.is-nightly == 'true')) &&
      (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))

    steps:
      - name: Download all artifacts
        if: needs.build.result == 'success'
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release archives
        if: needs.build.result == 'success'
        shell: bash
        run: |
          cd artifacts
          for dir in openblas-*; do
            if [[ "$dir" == *"windows"* ]]; then
              (cd "$dir" && zip -r "../${dir}.zip" .)
            else
              tar -czf "${dir}.tar.gz" -C "$dir" .
            fi
          done
          ls -la *.{tar.gz,zip} 2>/dev/null || echo "No archives created"

      - name: Update nightly release assets
        if: needs.check-version.outputs.is-nightly == 'true' && needs.build.result == 'success'
        shell: bash
        run: |
          if gh release view nightly >/dev/null 2>&1; then
            echo "Updating existing nightly release assets..."
            # Remove old assets but keep release
            gh release delete-asset nightly --yes $(gh release view nightly --json assets --jq '.assets[].name' | tr '\n' ' ') || true
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.check-version.outputs.is-nightly == 'true' && 'nightly' || format('{0}-build-{1}',
            needs.check-version.outputs.openblas-version, github.run_number) }}
          name: ${{ needs.check-version.outputs.is-nightly == 'true' && format('OpenBLAS {0} Nightly Build',
            needs.check-version.outputs.openblas-version) || format('OpenBLAS {0} Build {1}', needs.check-version.outputs.openblas-version,
            github.run_number) }}
          body: |
            ${{ needs.check-version.outputs.is-nightly == 'true' && format('Automated nightly build of OpenBLAS {0}

            **Version:** {0}
            **Commit:** {1}
            **Built:** {2}

            This release is updated weekly and contains the latest stable version of OpenBLAS compiled for multiple platforms.

            **Note:** This is a nightly build that gets overwritten weekly. For stable releases, use the tagged releases.', needs.check-version.outputs.openblas-version, needs.check-version.outputs.openblas-commit, github.run_id) || format('Build of OpenBLAS {0} for multiple platforms

            **Version:** {0}
            **Commit:** {1}
            **Build ID:** {2}', needs.check-version.outputs.openblas-version, needs.check-version.outputs.openblas-commit, github.run_number) }}
          draft: false
          prerelease: ${{ needs.check-version.outputs.is-nightly == 'true' }}
          files: ${{ needs.build.result == 'success' && 'artifacts/*.{tar.gz,zip}' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
