---
name: Lint

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    pre-commit:
        name: Pre-commit checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Run pre-commit
              uses: pre-commit/action@v3.0.1

    syntax:
        name: Shell syntax
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Test bash syntax
              run: |
                  find scripts -name "*.sh" -exec bash -n {} \;
